# This is a config file
filestorage:
  use_remote_aws: false
  local:
    local_path: 'static'
    hosted_path: 'http://s3.com'
  remote_aws:
    # Do NOT commit AWS secrets here. Use override.yaml
    # access_key: 'access_key'
    # secret_key: 'shhhhhhh'
    container: 'my-s3-bucket'
